config/routes.rb
Rails.application.routes.draw do
  root "products#index"
  resources :warehouses, only: [:new, :create]
  resources :inventories, only: [:update]
  resources :products, only: [:index, :edit], param: :sku_code
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/inventory.rb
class Inventory < ApplicationRecord

  # Associations
  belongs_to :product
  belongs_to :warehouse

  # Validations
  validates_numericality_of :product_count
  validate :exceeds_warehouse_max_capacity, if: [:warehouse_id?, :product_id?]

  def success_message
    "#{product_count} product('s) of '#{product.name}' are set for the warehouse in '#{warehouse.name}'"
  end
  # below will check whether upcoming inventory's product count exceeds the
  # warehouse max capacity
  def exceeds_warehouse_max_capacity
    changed_product_value = (self.product_count - self.product_count_was) rescue 0 
    total_product_count = changed_product_value + self.warehouse.item_count
    if total_product_count > self.warehouse.max_capacity
      errors.add(:base, "#{self.warehouse.name}'s warehouse max capacity reached!")
    end
  end

end

app/models/product.rb
class Product < ApplicationRecord
  # Associations
  has_many :inventories, dependent: :destroy
  has_many :warehouses, through: :inventories

  # Validations
  validates :sku_code, length: { is: 8 }
  validates_presence_of :name
  validates :price, presence: true, numericality: true

  before_validation(on: :create) do
    self.sku_code = SecureRandom.hex(4)
  end

  def self.table_header_names
    ['Sku-Code', 'Name'] + Warehouse.pluck(:name)
  end

  def self.table
    details = []
    product_data = {}
    column_names = []
    Product.all.each do |product|
      product_data = {
        "sku_code": product.sku_code,
        "name": product.name, 
      }
      Warehouse.all.each_with_index do |warehouse, index|
        product_data.merge!({
          "item_count_#{index}": (product.inventories.find_by_warehouse_id(warehouse.id).product_count rescue 0)
        })
      end
      details << product_data  
    end
    details.first.keys.each do |key|
      column_names << { data: key.to_s }
    end
    { details: details, column_names: column_names }
  end

  def to_param
    sku_code
  end
end

app/models/warehouse.rb
class Warehouse < ApplicationRecord

  # Associations
  has_many :inventories
  has_many :products, through: :inventories

  # Validations
  validates_presence_of :wh_code, :name, :pincode, :max_capacity
  validates :wh_code, length: { in: 4..16 }
  validates :pincode, length: { is: 6 }
  validates_numericality_of :max_capacity, :pincode

  # Callbacks
  before_validation(on: :create) do
    self.wh_code = SecureRandom.hex(8)
  end

  # Instance Methods

  # below will return the item count of the warehouse
  def item_count
    inventories.map(&:product_count).sum
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/inventories_controller.rb
class InventoriesController < ApplicationController
  def update
    inventory = Inventory.find(params[:id])
    inventory.update_attributes(inventory_param)
    respond_to do |format|
      if inventory.valid? 
        flash[:success] = inventory.success_message
      else
        flash[:danger] = inventory.errors.full_messages.to_sentence
      end
      format.html { redirect_to root_path }
    end
  end

  private

  def inventory_param
    params.require(:inventory).permit(:product_count)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :get_details, only: :edit

  def index
    @products = Product.table.to_json
    respond_to do |format|
      format.html
    end
  end

  def edit
    respond_to do |format|
      format.html 
      format.js 
    end
  end

  def get_details
    if params[:product_count].nil?
      @product = Product.find_by_sku_code(params[:sku_code])
      warehouse = (params[:wh_code].present? ? Warehouse.find_by_wh_code(params[:wh_code]) : nil)
      @inventory = Inventory.find_or_create_by(product: @product, warehouse: warehouse)
    else
      redirect_to root_path
    end  
  end
end

app/controllers/warehouses_controller.rb
class WarehousesController < ApplicationController
  def new
    @warehouse = Warehouse.new
  end

  def create
    @warehouse = Warehouse.new(warehouse_params)
    respond_to do |format|
      if @warehouse.valid?
        @warehouse.save
        format.html { redirect_to products_path, success: 'Warehouse created' }
      else
        format.html { render :new }
      end
    end
  end

  private

  def warehouse_params
    params.require(:warehouse).permit(:name, :pincode, :max_capacity)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/inventories_helper.rb
module InventoriesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/warehouses_helper.rb
module WarehousesHelper
end

app/views/inventories/update.html.erb
<h1>Inventories#update</h1>
<p>Find me in app/views/inventories/update.html.erb</p>

app/views/layouts/_messages.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %> mb-0 error-message">
    <ul>
      <li>
        <%= value %>
      </li>
    </ul>
  </div>
<% end %>

<script type="text/javascript">
  $(document).on('turbolinks:load', function(){
    $(".error-message").slideUp(2500);
  })
</script>  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>InventoryManagementSystem</title>
    <%= csrf_meta_tags %>
    <meta charset="utf-8">
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@10"></script>
  </head>

  <body>
    <%= render 'layouts/messages' %> 
    <%= yield %>
  </body>
</html>

app/views/products/edit.html.erb
<h1 class="text-center"> Set an item count</h1>

<form>
  <div class="form-group row justify-content-center mt-3">
    <label for="sku_code" class="col-md-2 col-form-label">Sku Code</label>
    <div class="col-md-3">
      <%= text_field_tag :sku_code, @product.sku_code, id: 'sku_code', class: 'form-control', disabled: true  %>
    </div>
  </div>
  <div class="form-group row justify-content-center my-3">
    <label for="name" class="col-md-2 col-form-label">Product Name</label>
    <div class="col-md-3">
      <%= text_field_tag :name, @product.name , id: "name", 
      class: 'form-control', disabled: true  %>
    </div>
  </div>
  <div class="form-group row justify-content-center mb-3">
    <label for="price" class="col-md-2 col-form-label">Price</label>
    <div class="col-md-3">
      <%= text_field_tag :price, @product.price, id: 'price', 
      class: 'form-control', disabled: true  %>
    </div>
  </div>
  <div class="form-group row justify-content-center mb-3">
    <label for="select_warehouse" class="col-md-2 col-form-label">Select Warehouse</label>
    <div class="col-md-3">
    <%= select_tag 'Select Warehouse', options_from_collection_for_select(Warehouse.all, "wh_code", "name"), include_blank: 'Select', class: 'form-control', id: 'select_warehouse' %>
    </div>
  </div>
  <div id="warehouse_details"></div> 
</form>

<script>
  $(document).ready(function(){
    $('#select_warehouse').click(function(){
      $.ajax({
        method: 'GET',
        url: "<%= "#{edit_product_path(@product, format: :js)}" %>",
        data: { wh_code: $(this).val() }
      });
    })
  })
</script>

app/views/products/edit.js.erb
$("#warehouse_details").html('<%= j render 'products/partials/set_item_count', inventory: "#{@inventory}" %>');

app/views/products/index.html.erb
<h1 class="text-center">Inventory Management System</h1>

<%= link_to 'Add Warehouse', new_warehouse_path, class: 'btn btn-primary float-right mb-3' %>

<table id="products" class="table table-striped table-bordered cell-border text-center">
  <thead>
    <tr>
      <% Product.table_header_names.each do |column_name| %>
        <td><%= column_name %></td>
      <% end %>
    </tr>
  </thead>
</table>

<script>
  $(document).on('turbolinks:load', function(){
    var table_data = <%= "#{@products}".html_safe %>

    if ($("#products_wrapper").length == 0) {
      $('#products').dataTable({
        data: table_data['details'],
        columns: table_data['column_names'],
        rowCallback: function(row, data, index) {
          for(i in data){
            if (typeof data[i] == 'number' && data[i] < 10){
              $(row).find('td').filter(function(){ return $(this).text() == data[i] }).addClass('bg-danger text-white')   
            }  
          }
        },
        columnDefs: [
          {
            targets: 0,
            render: function ( data, type, row, meta ) {
              if(type === 'display'){
                data = '<a href="'+ window.location.origin + '/products/' + (data) + '/edit/">' + data + '</a>';
              }
              return data;
            }
          }
        ]
      })
    }  
  })
</script>

app/views/products/partials/_set_item_count.html.erb
<% if @inventory.present? %> 
  <form>
    <div class="form-group row justify-content-center mt-3">
      <label for="wh_code" class="col-md-2 col-form-label">Wh Code</label>
      <div class="col-md-3">
        <%= text_field_tag :wh_code, @inventory.warehouse.wh_code, id: 'wh_code', class: 'form-control', disabled: true  %>
      </div>
    </div>
    <div class="form-group row justify-content-center my-3">
      <label for="name" class="col-md-2 col-form-label">Warehouse Name</label>
      <div class="col-md-3">
        <%= text_field_tag :name, @inventory.warehouse.name , id: "name", 
        class: 'form-control', disabled: true  %>
      </div>
    </div>
    <div class="form-group row justify-content-center mb-3">
      <label for="pincode" class="col-md-2 col-form-label">Pincode</label>
      <div class="col-md-3">
        <%= text_field_tag :pincode, @inventory.warehouse.pincode, id: 'pincode', 
        class: 'form-control', disabled: true  %>
      </div>
    </div>
   <div class="form-group row justify-content-center mt-3">
     <label for="product_count" class="col-md-2 col-form-label">Product count</label>
     <div class="col-md-3">
       <%= text_field_tag :product_count, @inventory.product_count, class: 'product_count form-control' %>
     </div>
   </div>
   <div class="form-group row justify-content-center mt-3">
     <div class="col-md-5">
       <%= link_to 'Back', products_path, class: 'btn btn-danger' %>
       <%= button_tag :submit, class: 'update_inventory float-right btn btn-success' %>
     </div>
   </div>
  </form>  
<% end %>

<script>
  $(document).ready(function(){
    $('.update_inventory').on('click' ,function(){
      $.ajax({
        method: 'PATCH',
        url: "<%= "#{inventory_path(@inventory, format: :html)}" %>",
        data: { inventory: { product_count: $('.product_count').val() } },
        headers: {
          'X-CSRF-Token': '<%= form_authenticity_token.to_s %>'
        },
        success: function(){
          debugger;
        }
      });
    })
  });  
</script>

app/views/warehouses/new.html.erb
<h1 class="text-center"> Create new warehouse</h1>

<%= form_for :warehouse, url: warehouses_path, class: 'warehouse_form', method: :create do |f| %>
  <form>
    <div class="form-group row justify-content-center mt-3">
      <label for="name" class="col-md-2 col-form-label">Name</label>
      <div class="col-md-3">
        <%= f.text_field :name, placeholder: 'Enter name', id: 'name', class: 'name form-control' %>
      </div>
    </div>
    <div class="form-group row justify-content-center my-3">
      <label for="pincode" class="col-md-2 col-form-label">Pincode</label>
      <div class="col-md-3">
        <%= f.number_field :pincode, placeholder: 'Enter Pincode', id: "pincode", 
        class: 'form-control', minlength: 6, maxlength: 6 %>
      </div>
    </div>
    <div class="form-group row justify-content-center mb-3">
      <label for="max_capacity" class="col-md-2 col-form-label">Max Capacity</label>
      <div class="col-md-3">
        <%= f.number_field :max_capacity, placeholder: 'Enter Max Capacity', id: 'max_capacity', 
        class: 'form-control' %>
      </div>
    </div> 
    <div class="form-group row justify-content-center mt-3">
      <div class="col-md-5">
        <%= link_to 'Back', products_path, class: 'btn btn-danger' %>
        <%= f.submit :submit, class: 'float-right btn btn-success' %>
      </div>
    </div>
  </form>
<% end %>

<script>
  $(document).on('turbolinks:load', function(){

    if(<%= "#{@warehouse.errors.present?}" %>){
      Swal.fire({
        title: "Errors!",
        html: "<%= "#{@warehouse.errors.full_messages.to_sentence}".html_safe %>",
        icon: "error",
      })
    }
  })
</script>